# Generated by Django 3.1.7 on 2021-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('persoans', models.CharField(max_length=40)),
                ('fechas', models.CharField(max_length=40)),
                ('hora', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=60)),
            ],
        ),
    ]
